spring.application.name=railway-ticket-system

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/rdb_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# File upload for tickets (create folder tickets/ in project root)
app.ticket.storage.path=./tickets

# NEW: Mail Config (use your Gmail credentials for testing)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=chasheemahasini@gmail.com
spring.mail.password=rgcikqzrxziseeio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# OTP Config
app.otp.expiration.minutes=5